import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar"
import Footer from "./Components/Footer"
import Marquee from "react-fast-marquee";
import { FaCircle } from "react-icons/fa";
import AuthProviders from "./providers/AuthProviders";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased min-h-screen flex flex-col`}
      >
        <AuthProviders>
          {/* <Marquee> */}
          {/* Top Section */}
          <Marquee className="lg:py-3 bg-black text-white text-lg font-bold" speed={60}>
            <p >10% Flat discount at order over BDT 999!</p>
            <FaCircle className="px-4 text-white text-5xl" />
            <p >20% Flat discount at order over BDT 1999!</p>
            <FaCircle className="px-4 text-white text-5xl" />
          </Marquee>

          <div className="sticky top-0 z-50 bg-[#F0F0F0]">
            <Navbar />
          </div>

          {/* Main Content Area — auto grows */}
          <main className="grow">
            {children}
            {/* 🔥 Global Toaster */}
            <Toaster
              position="top-right"
              reverseOrder={false}
            />
          </main>

          {/* Bottom Section */}
          <Footer />
        </AuthProviders>
      </body>
    </html>
  );
}
